package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildIos'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildIos")) {
    check(publishArtifacts == PublishMode.NORMALLY_FINISHED) {
        "Unexpected option value: publishArtifacts = $publishArtifacts"
    }
    publishArtifacts = PublishMode.SUCCESSFUL
}
