package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.CommitStatusPublisher
import jetbrains.buildServer.configs.kotlin.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'PrValidation'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("PrValidation")) {
    features {
        val feature1 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                vcsRootExtId = "${DslContext.settingsRoot.id}"
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = personalToken {
                        token = "%github.token%"
                    }
                }
            }
        }
        feature1.apply {
            publisher = github {
                statusCheckName = ""
                githubUrl = "https://api.github.com"
                authType = personalToken {
                    token = "credentialsJSON:62de9edd-c72c-4200-bf60-47cf6da7be0a"
                }
            }
        }
    }
}
